# Generated by Django 5.2.5 on 2025-08-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.URLField(max_length=500),
        ),
    ]
