# Generated by Django 5.2.5 on 2025-08-25 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_friends"),
    ]

    operations = [
        migrations.AlterField(
            model_name="likes",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="api.post",
            ),
        ),
    ]
